### PR TITLE
Add turkish locales

### PR DESCRIPTION
**Pull request by mikropsoft**
Add turkish locales and fix es string on en strings

### CODE REVIEW

**Comment by mikropsoft** [comment]
Hello, I think I need to edit the "strings.g.dart" file for the translation to work, right? I will commit again after a while. It would be good if you tell me if there are places in the file that I should pay attention to.

**Comment by JGeek00** [comment]
No, the ``strings.g.dart`` must not be edited. To enable the translation you need to add a new entry on ``main.dart``, on the ``supportedLocales`` array. Then run ``flutter pub get`` to generate the translations.

**Comment by mikropsoft** [comment]
> No, the ``strings.g.dart`` must not be edited. To enable the translation you need to add a new entry on ``main.dart``, on the ``supportedLocales`` array. Then run ``flutter pub get`` to generate the translations.

Can you give me an example of the code to be written exactly in that section?

**Comment by JGeek00** [comment]
```dart
          supportedLocales: const [
            Locale('en', ''),
            Locale('es', ''),
            Locale('de', ''),
            Locale('pl', ''),
          ],
```
There you have to add another entry with the new language. I don't know what localization code is the turkish language, but you will have to add something like this ``Locale('tk', '')`` (assuming that turkish is tk).

**Comment by mikropsoft** [comment]
> ```dart
>           supportedLocales: const [
>             Locale('en', ''),
>             Locale('es', ''),
>             Locale('de', ''),
>             Locale('pl', ''),
>           ],
> ```
> 
> There you have to add another entry with the new language. I don't know what localization code is the turkish language, but you will have to add something like this `Locale('tk', '')` (assuming that turkish is tk).

I think it happened, pub get did not give error

**Comment by mikropsoft** [comment]
oh, I guess I have to add other languages for that, right?

**Comment by JGeek00** [comment]
Ah sorry, I gave you the wrong instructions. That's the process for the old system that I'm using on the other projects. At the end of the readme you have the correct instructions to add a new language.

**Comment by mikropsoft** [comment]
> Ah sorry, I gave you the wrong instructions. That's the process for the old system that I'm using on the other projects. At the end of the readme you have the correct instructions to add a new language.

Done :)

**Pull request merged**
